#!/usr/bin/env python3
"""Plot workflow_perf/v1 JSONL as grouped column charts (one chart per stat).

Reads docs/perf/history/workflow_history.jsonl if non-empty, else
workflow_history.example.jsonl (synthetic).

Outputs docs/perf/history/plots/workflow_*_over_time.png
"""

from __future__ import annotations

import json
from pathlib import Path

# Must match expat_app/lib/services/perf_workflow_ids.dart chartOrder
WORKFLOW_ORDER = [
    "landlord_listing_upload",
    "message_translate",
    "rides_estimate",
    "explore_places",
    "listing_assignment",
]

WORKFLOW_LABELS = {
    "landlord_listing_upload": "Landlord listing",
    "message_translate": "Message translate",
    "rides_estimate": "Rides + estimate",
    "explore_places": "Explore (Places)",
    "listing_assignment": "Listing assignment",
}

STATS = ["avg_ms", "max_ms", "p90_ms"]


def load_runs(root: Path) -> tuple[list[dict], Path]:
    hist = root / "docs" / "perf" / "history" / "workflow_history.jsonl"
    example = root / "docs" / "perf" / "history" / "workflow_history.example.jsonl"
    path = hist
    if not hist.is_file() or hist.stat().st_size == 0:
        path = example
    runs: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        runs.append(json.loads(line))
    return runs, path


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    runs, source = load_runs(root)
    if not runs:
        print("No JSONL rows to plot.", file=__import__("sys").stderr)
        return 1

    try:
        import matplotlib.pyplot as plt
        from datetime import datetime
    except ImportError:
        print("pip install matplotlib", file=__import__("sys").stderr)
        return 1

    out_dir = root / "docs" / "perf" / "history" / "plots"
    out_dir.mkdir(parents=True, exist_ok=True)

    dates = [datetime.fromisoformat(r["recorded_at"].replace("Z", "+00:00")) for r in runs]
    x = range(len(dates))
    n_wf = len(WORKFLOW_ORDER)
    width = 0.8 / max(n_wf, 1)
    offsets = [(i - (n_wf - 1) / 2) * width for i in range(n_wf)]

    for stat in STATS:
        fig, ax = plt.subplots(figsize=(11, 5), layout="constrained")
        for wi, wf in enumerate(WORKFLOW_ORDER):
            ys: list[float] = []
            for r in runs:
                block = (r.get("workflows") or {}).get(wf) or {}
                v = block.get(stat)
                ys.append(float(v) if v is not None else float("nan"))
            xpos = [xi + offsets[wi] for xi in x]
            ax.bar(
                xpos,
                ys,
                width * 0.92,
                label=WORKFLOW_LABELS.get(wf, wf),
            )

        ax.set_xticks(list(x))
        ax.set_xticklabels([d.strftime("%Y-%m-%d") for d in dates], rotation=25, ha="right")
        ax.set_ylabel(f"{stat.replace('_', ' ')} (lower is faster)")
        ax.set_xlabel("Probe run date (UTC)")
        ax.legend(loc="upper right", fontsize=8, ncol=2)
        title_stat = stat.replace("_", " ").upper()
        ax.set_title(
            f"Workflow performance over time — {title_stat}\n"
            f"(source: {source.relative_to(root)})"
        )
        ax.grid(axis="y", alpha=0.3)

        png = out_dir / f"workflow_{stat}_over_time.png"
        fig.savefig(png, dpi=150, facecolor="white")
        plt.close(fig)
        print(f"Wrote {png}")

    disclaimer = out_dir / "README.txt"
    disclaimer.write_text(
        "Generated by scripts/plot_workflow_timeseries.py.\n"
        "If the source was workflow_history.example.jsonl, values are SYNTHETIC.\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
